# Generated by Django 4.0.6 on 2022-07-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teste',
            old_name='idade',
            new_name='idade_pessoa',
        ),
    ]
