# Generated by Django 4.0.6 on 2022-07-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_idade_teste_idade_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
